// lib/data.ts
// Functions to load JSON data files from the /data/ directory
// These run at build time (Server Components) for SSG

import path from "path";
import fs from "fs";
import type {
    BreadthDataPoint,
    PerformanceRow,
    MarketStatus,
    MarketStatusEntry,
    ConstituentPerformanceMap,
    RRGDataPoint,
} from "@/types";
import { BROAD_MARKET, INDUSTRIES, SECTORS } from "@/lib/config";
import { resolveDataKey } from "./utils";


const DATA_DIR = path.join(process.cwd(), "data");

function readJson<T>(filePath: string): T | null {
    try {
        const fullPath = path.join(DATA_DIR, filePath);
        const raw = fs.readFileSync(fullPath, "utf-8");
        return JSON.parse(raw) as T;
    } catch {
        return null;
    }
}

export function getBreadthData(indexId: string): BreadthDataPoint[] {
    return readJson<BreadthDataPoint[]>(`breadth/${indexId}.json`) ?? [];
}

export function getLatestDataDate(): string | null {
    const data = getBreadthData("market_breadth_nifty500");
    if (data.length === 0) return null;
    return data[data.length - 1].Date;
}

export function getPerformanceSummary(): PerformanceRow[] {
    return readJson<PerformanceRow[]>("performance/performance_summary.json") ?? [];
}

export function getMarketStatus(): MarketStatus {
    return readJson<MarketStatus>("market_status/market_status_latest.json") ?? {};
}

export function getConstituentPerformance(): ConstituentPerformanceMap {
    return (
        readJson<ConstituentPerformanceMap>(
            "constituent_performance/constituent_performance_latest.json"
        ) ?? {}
    );
}

/**
 * Look up market status for a given config title.
 * The market_status JSON uses varied key formats:
 *  - Broad market: "Nifty 50", "Nifty 500", "Nifty Smallcap 250"
 *  - Sectors: "NIFTY AUTO", "NIFTY BANK", etc.
 *  - Industries: "Copper", "Defence & Aerospace", "Railways & Infrastructure" etc.
 *
 * We need to match the config title to the market status key.
 */
export function getMarketStatusForIndex(configTitle: string): MarketStatusEntry | null {
    const status = getMarketStatus();

    // Direct match
    if (status[configTitle]) return status[configTitle];

    // Try uppercase (e.g., "Nifty Auto" → "NIFTY AUTO")
    const upperKey = configTitle.toUpperCase();
    if (status[upperKey]) return status[upperKey];

    // Try removing "Nifty " prefix (e.g., "Nifty Consumer Durables" → "NIFTY CONSUMER DURABLES")
    if (configTitle.startsWith("Nifty ")) {
        const niftyUpper = "NIFTY " + configTitle.slice(6).toUpperCase();
        if (status[niftyUpper]) return status[niftyUpper];
    }

    // Try all keys case-insensitive using centralized resolveDataKey
    const resolvedTitle = resolveDataKey(configTitle);

    for (const key of Object.keys(status)) {
        if (key.toLowerCase() === resolvedTitle) return status[key];
    }

    return null;
}

export function getRRGData(timeframe: "D" | "W" | "M"): RRGDataPoint[] {
    return readJson<RRGDataPoint[]>(`rrg/rrg_${timeframe}.json`) ?? [];
}

export interface ThemeBreadthSummary {
    id: string;
    title: string;
    category: string;
    data: { Date: string; Index_Close: number }[];
}

/**
 * Load Index_Close time series for every industry theme.
 * Runs at build time (SSG). Returns full history so client can slice dynamically.
 */
export function getAllThemeBreadthData(): ThemeBreadthSummary[] {
    const results: ThemeBreadthSummary[] = [];
    const configs = [...BROAD_MARKET, ...SECTORS, ...INDUSTRIES];

    for (const config of configs) {
        const raw = getBreadthData(config.dataFile);
        if (!raw || raw.length === 0) continue;

        const trimmed = raw
            .filter((d) => d.Index_Close != null)
            .map((d) => ({ Date: d.Date, Index_Close: d.Index_Close! }));

        if (trimmed.length > 0) {
            results.push({ id: config.id, title: config.title, category: config.category, data: trimmed });
        }
    }

    return results;
}

export interface StockSearchEntry {
    id: string;
    title: string;
    category: string;
}

export type StockSearchIndex = Record<string, StockSearchEntry[]>;

/**
 * Load the pre-built reverse index: ticker → themes/sectors it belongs to.
 * Generated by export_json.py → stock_search_index.json
 */
export function getStockSearchIndex(): StockSearchIndex {
    return readJson<StockSearchIndex>("search/stock_search_index.json") ?? {};
}
